# -*- coding: utf-8 -*-
"""day5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rF_NCJpB1cCjjtJVrVDRlDCOYAMrdrVh
"""

fruits=["Apple","Peach","Pear"]
for fruit in fruits:
  print(fruit)

fruits=["Apple","Peach","Pear"]
for fruit in fruits:
  print(fruit)
  print(fruit+" Pie")

student_heights = input("Input a list of student heights ").split()
for n in range(0, len(student_heights)):
  student_heights[n] = int(student_heights[n])
print(student_heights)
total_height=0
total_students=0
for height in student_heights:
  total_height=total_height+height
for student in student_heights:
  total_students=total_students+1
print(round(total_height/total_students))

#78 65 89 86 55 91 64 89
student_scores = input("Input a list of student scores ").split()
for n in range(0, len(student_scores)):
  student_scores[n] = int(student_scores[n])
print(student_scores)
max_score=0
for score in student_scores:
  if score>max_score:
    max_score=score
print("The highest score in the class is:",max_score)

numbers=0
for number in range(1,101):
  numbers=numbers+number
print(numbers)

total=0
for number in range(0,101,2):
  total=total+number
print(total)

#FizzBuzz
contador=1
for number in range(contador,16):
  if number%5==0 and number%3==0:
    print("FizzBuzz")
  elif number%5==0:
    print("Buzz")
  elif number%3==0:
    print("Fizz")
  else:
    print(number)

import random
letters_list = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
numbers_list = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
symbols_list = ['!', '#', '$', '%', '&', '(', ')', '*', '+']
l0=[]
n0=[]
s0=[]
print("Welcome to the PyPassword Generator!")
letters= int(input("How many letters would you like in your password?\n")) 
for letter in range(1,letters+1):
  l1=random.choice(letters_list)
  l0.append(l1)
symbols = int(input(f"How many symbols would you like?\n"))
for symbol in range(1,symbols+1):
  s1=random.choice(symbols_list)
  s0.append(s1)
numbers = int(input(f"How many numbers would you like?\n"))
for number in range(1,numbers+1):
  n1=random.choice(numbers_list)
  n0.append(n1)
t0=l0+s0+n0
print(t0)
random.shuffle(t0)
print(t0)
password=''
for char in t0:
  password=password+char
print(f"Your password is: {password}")