# -*- coding: utf-8 -*-
"""day7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rF_NCJpB1cCjjtJVrVDRlDCOYAMrdrVh
"""

import random

word_list=["ardvark", "baboon", "camel"]

chosen_word=random.choice(word_list)

guess=input("Guess a letter: ")
guess=guess.lower()

guess=input("Guess a letter: ")
guess=guess.lower()

display=[]
for i in chosen_word:
  display += "_"
print(display)

for position in range(len(chosen_word)):
  letter=chosen_word[position]
  if letter==guess:
    display[position]=letter
print(display)

import random

stages = ['''
  +---+
  |   |
  O   |
 /|\  |
 / \  |
      |
=========
''', '''
  +---+
  |   |
  O   |
 /|\  |
 /    |
      |
=========
''', '''
  +---+
  |   |
  O   |
 /|\  |
      |
      |
=========
''', '''
  +---+
  |   |
  O   |
 /|   |
      |
      |
=========''', '''
  +---+
  |   |
  O   |
  |   |
      |
      |
=========
''', '''
  +---+
  |   |
  O   |
      |
      |
      |
=========
''', '''
  +---+
  |   |
      |
      |
      |
      |
=========
''']


word_list=["ardvark", "baboon", "camel"]

chosen_word=random.choice(word_list)

display=[]
for i in chosen_word:
  display += "_"
print(display)

end_of_game = False

while "_" in display:
  guess=input("Guess a letter: ")
  guess=guess.lower()
  for position in range(len(chosen_word)):
    letter=chosen_word[position]
    if letter==guess:
      display[position]=letter
  print(display)

import random
import hangman_words
logo="""
  _                                             
 | |                                            
 | |__   __ _ _ __   __ _ _ __ ___   __ _ _ __  
 | '_ \ / _` | '_ \ / _` | '_ ` _ \ / _` | '_ \ 
 | | | | (_| | | | | (_| | | | | | | (_| | | | |
 |_| |_|\__,_|_| |_|\__, |_| |_| |_|\__,_|_| |_|
                     __/ |                      
                    |___/                       
"""
stages = ['''
  +---+
  |   |
  O   |
 /|\  |
 / \  |
      |
=========
''', '''
  +---+
  |   |
  O   |
 /|\  |
 /    |
      |
=========
''', '''
  +---+
  |   |
  O   |
 /|\  |
      |
      |
=========
''', '''
  +---+
  |   |
  O   |
 /|   |
      |
      |
=========''', '''
  +---+
  |   |
  O   |
  |   |
      |
      |
=========
''', '''
  +---+
  |   |
  O   |
      |
      |
      |
=========
''', '''
  +---+
  |   |
      |
      |
      |
      |
=========
''']

word_list=hangman_words.word_list

chosen_word=random.choice(word_list)
print(logo)
print(f'Pssst, the solution is {chosen_word}.')
display=[]
for i in chosen_word:
  display += "_"

lives=6

end_of_game = False

while not end_of_game:
  guess=input("Guess a letter: ")
  guess=guess.lower()
  if guess in display:
    print(f"You've already guessed {guess}")
  for position in range(len(chosen_word)):
    letter=chosen_word[position]
    if letter==guess:
      display[position]=letter
  if guess not in chosen_word:
    print(f"You guessed {guess}, that's not in the word. You lose a life")
    lives -= 1  
  if lives == 0:
    end_of_game=True
    print("You lose")
    print(f"The word was{chosen_word}")
  
  print(f"{' '.join(display)}")
  if "_" not in display:
    end_of_game=True
    print("You win")
  print(stages[lives])