# -*- coding: utf-8 -*-
"""day14ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rF_NCJpB1cCjjtJVrVDRlDCOYAMrdrVh

## Higher or lower
"""

import random as rd
from art import logo, vs
from data import data
from IPython.display import clear_output 

l0=[]

l1=[]



def contest(list1, data1):
  """Define the number of the contestant
  """
  list1.append(rd.randint(0,len(data1)-1))
  return list1


def participants(dict1, list1):
  """ Define the info of the contestant"""
  list_info=[]
  for i in range(2):
    list_info.append(dict1[list1[i]].get("name"))
    list_info.append(dict1[list1[i]].get("description"))
    list_info.append(dict1[list1[i]].get("country"))
    list_info.append(dict1[list1[i]].get("follower_count"))
  return list_info



def comparator(selector, other, list1, list2):
  """ Compares the number of followers
  of the contestants and decides a winner"""
  score=0 #Globales
  should_end = False #Globales
  while not should_end:
    clear_output()
    if selector > other:
      print(logo)
      score += 1
      print(f"You're right! Current score: {score}")
      
      for i in range(0,4):
        list1.pop(0)
      list2.pop(0)
      contest(list2,data)
      list1=participants(data,list2)
      print(f"Compare A: {list1[0]}, a {list1[1]}, from {list1[2]}.")
      print(vs)
      print(f"Against B: {list1[4]}, a {list1[5]}, from {list1[6]}.")
      selector=input("Who has more followers? Type 'A' or 'B': ")
      if selector=="A" or "a":
        selector=list1[3]
        other=list1[7]
      else:
        selector=list1[7]
        selector[3]
      clear_output()
    else:
      print(logo)
      print(f"Sorry, final score: {score}")
      return


def begin():
  contest(l0,data)
  contest(l0,data)
  
  if l0[0]==l0[1]:
    l0[1]=rd.randint(0,len(data)-1)

  print(l0)
  info=participants(data,l0)

  score_a=info[3]
  score_b=info[7]
  print(logo)
  print(f"Compare A: {info[0]}, a {info[1]}, from {info[2]}.")
  print(vs)
  print(f"Against B: {info[4]}, a {info[5]}, from {info[6]}.")
  other=0
  selector=input("Who has more followers? Type 'A' or 'B': ")

  if selector=="A" or selector=="a":
    selector = score_a
    other = score_b
  else:
    selector = score_a
    other = score_b
  comparator(selector, other, info, l0)
   



begin()

