# -*- coding: utf-8 -*-
"""day4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rF_NCJpB1cCjjtJVrVDRlDCOYAMrdrVh
"""

import random
value=random.randint(0,1)
if value==0:
  print("heads")
else:
  print("tails")

import random
value=random.randint(0,3)
print(value)

test_seed = int(input("Create a seed number: "))
random.seed(test_seed)
t=str(test_seed)
if t.count("4")>=2:
  print("Tails")
else:
  print("Heads")

test_seed = int(input("Create a seed number: "))
random.seed(test_seed)

# Split string method
names_string = input("Give me everybody's names, separated by a comma. ")
names = names_string.split(", ")
a=(len(names)-1)
choice=names[random.randint(0,a)]
print(f"{choice} is going to buy the meal today!")

row1 = ["⬜️","⬜️","⬜️"]
row2 = ["⬜️","⬜️","⬜️"]
row3 = ["⬜️","⬜️","⬜️"]
map = [row1, row2, row3]
print(f"{row1}\n{row2}\n{row3}")
position = input("Where do you want to put the treasure? ")
a=int(position)
column=a//10
row=a-column*10
b=column-1
c=row-1
map[c][b]="X"
print(f"{row1}\n{row2}\n{row3}")

import random
rock = '''
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
'''

paper = '''
    _______
---'   ____)____
          ______)
          _______)
         _______)
---.__________)
'''

scissors = '''
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
'''
rps=[rock,paper,scissors]
a=int(input("What do you choose? Type 0 for Rock, 1 for Paper or 2 for Scissors.\n"))
if a==0:
  print(rock)
elif a==1:
  print(paper)
elif a==2:
  print(scissors)
else:
  print("Choose a valid option.")
print("Computer choose: ")
b=random.randint(0,2)
print(rps[b])
if a==b:
  print("It's a draw")
elif a==0:
  if b==2:
    print("You win!")
  else:
    print("You lose")
elif a==1:
  if b==0:
    print("You win!")
  else:
    print("You lose")
elif a==2:
  if b==1:
    print("You win!")
  else:
    print("You lose")